@startuml
package domain {
    +class Deck {
        -deck: ArrayList<Card>

        +Deck()
        +shuffle(): void
        +draw(): Card
    }

    +class Card {
        -{final} value: CardValue
        -{final} suit: CardSuit

        +Card(value: Value, suit: Suit)
        +getValue(): CardValue
        +getSuit(): CardSuit
    }

    +enum CardSuit {
        HEART,
        DIAMOND,
        CLUB,
        SPADE
    }
    +enum CardValue {
        NINE,
        TEN,
        JACK,
        QUEEN,
        KING,
        ACE
    }

    +class Game {
        -tOne: Team
        -tTwo: Team
        -deck: Deck

        +game(pOne: Player, pTwo: Player, pThree: Player, pFour: Player)
        +deal(): void
        +checkWin(): Team
        +updateScore(): void
    }

    +class Team {
        -pOne: Player
        -pTwo: Player

        +Team(pOne: Player, pTwo: Player)
        +calledTrump(): boolean
        +tricksWon(): int

    }

    +class Player {
        -name: String
        -tricksWon: int
        -calledTrump: boolean

        +Player(name: String)
        +addTrick(): void
        +resetTricks(): void
        +setCalledTrump(): void

    }
}
package interface {

}

Deck --> "*" Card
Card --> CardSuit
Card --> CardValue
Game --> "*" Team
Game --> Deck
Team --> "*" Player


@enduml
--> for association, ..> for dependency, ..|> for implementation, and --|> for inheritance.
